import type { Metadata } from "next";
import { Geologica } from "next/font/google";
import "./globals.css";

// ⬇️ Componentes do layout
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geologica = Geologica({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  display: "swap",
  fallback: ["sans-serif", "serif"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geologica.variable} antialiased`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
